image: berenger/tbfmmci

tbfmm-gcc-inastemp-spetabaru:
  tags:
    - medium
  script:
    - g++-7 --version
    - cmake --version
    - git submodule init
    - git submodule update
    - mkdir build
    - cd build
    - CXX=g++-7 cmake -DBUILD_TESTS=ON ..
    - make
    - CTEST_OUTPUT_ON_FAILURE=TRUE make test
   

tbfmm-clang-inastemp-spetabaru:
  tags:
    - medium
  script:
    - clang++-8 --version
    - cmake --version
    - git submodule init
    - git submodule update
    - mkdir build
    - cd build
    - CXX=clang++-8 cmake -DBUILD_TESTS=ON ..
    - make
    - CTEST_OUTPUT_ON_FAILURE=TRUE make test
  dependencies:
    - tbfmm-gcc-inastemp-spetabaru

tbfmm-gcc-no-modules:
  tags:
    - medium
  script:
    - g++-7 --version
    - cmake --version
    - mkdir build
    - cd build
    - CXX=g++-7 cmake -DBUILD_TESTS=ON ..
    - make
    - CTEST_OUTPUT_ON_FAILURE=TRUE make test
  dependencies:
    - tbfmm-clang-inastemp-spetabaru


tbfmm-clang-no-modules:
  tags:
    - medium
  script:
    - clang++-8 --version
    - cmake --version
    - mkdir build
    - cd build
    - CXX=clang++-8 cmake -DBUILD_TESTS=ON ..
    - make
    - CTEST_OUTPUT_ON_FAILURE=TRUE make test
  dependencies:
    - tbfmm-gcc-no-modules

tbfmm-full-coverage:
  tags:
    - large
  script:
    - g++-7 --version
    - cmake --version
    - git submodule init
    - git submodule update
    - mkdir build
    - cd build
    - CXX=g++-7 cmake -DCMAKE_BUILD_TYPE=Debug -DUSE_COVERAGE=ON -DBUILD_TESTS=ON ..
    - make
    - CTEST_OUTPUT_ON_FAILURE=TRUE make test
    - lcov --directory CMakeFiles/ --directory unit-tests/CMakeFiles/ -c -o coverage-rapport.info
    - lcov --list coverage-rapport.info
    - genhtml -o ../coverage -t "Coverage tbfmm" coverage-rapport.info
  artifacts:
    paths:
      - coverage/
  dependencies:
    - tbfmm-clang-no-modules

pages:
  stage: deploy
  dependencies:
    - tbfmm-full-coverage
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master

