image: berenger/spetabaruci

tbfmm:
  tags:
    - medium
  script:
    - git submodule init
    - git submodule update
    - mkdir build
    - cd build
    - CXX=g++-7 cmake -DBUILD_TESTS=ON ..
    - make
    - CTEST_OUTPUT_ON_FAILURE=TRUE make test

tbfmm-full:
  tags:
    - medium
  script:
    - git submodule init
    - git submodule update
    - mkdir build
    - cd build
    - CXX=g++-7 cmake -DBUILD_TESTS=ON -DUSE_SIMU_TESTING=ON ..
    - make
    - CTEST_OUTPUT_ON_FAILURE=TRUE make test
#  only:
#    - mergerequests

tbfmm-full-coverage:
  tags:
    - medium
  script:
    - git submodule init
    - git submodule update
    - mkdir build
    - cd build
    - CXX=g++-7 cmake -DCMAKE_BUILD_TYPE=Debug -DUSE_COVERAGE=ON -DBUILD_TESTS=ON -DUSE_SIMU_TESTING=ON ..
    - make
    - CTEST_OUTPUT_ON_FAILURE=TRUE make test
    - lcov --directory CMakeFiles/ --directory unit-tests/CMakeFiles/ -c -o coverage-rapport.info
    - lcov --list coverage-rapport.info
    - genhtml -o ../coverage -t "Coverage tbfmm" coverage-rapport.info
  artifacts:
    paths:
      - coverage/

pages:
  stage: deploy
  dependencies:
    - tbfmm-full-coverage
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master

