image: berenger/tbfmmci

stages:
  - nomodules
  - release
  - coverage
  - deploy

tbfmm-gcc-inastemp-spetabaru:
  tags:
    - large
  script:
    - g++-7 --version
    - cmake --version
    - git submodule init
    - git submodule update
    - mkdir build
    - cd build
    - CXX=g++-7 cmake -DBUILD_TESTS=ON ..
    - make -j 2
    - CTEST_OUTPUT_ON_FAILURE=TRUE OMP_PROC_BIND=FALSE OMP_NUM_THREADS=3 ./unit-tests/utest-testkernel-spetabaru-float
  stage: release
   

tbfmm-clang-inastemp-spetabaru:
  tags:
    - large
  script:
    - clang++-8 --version
    - cmake --version
    - git submodule init
    - git submodule update
    - mkdir build
    - cd build
    - CXX=clang++-8 cmake -DBUILD_TESTS=ON ..
    - make -j 2
    - CTEST_OUTPUT_ON_FAILURE=TRUE OMP_PROC_BIND=FALSE OMP_NUM_THREADS=3 ./unit-tests/utest-testkernel-spetabaru-float
  stage: release

tbfmm-full-coverage:
  tags:
    - large
  script:
    - g++-7 --version
    - cmake --version
    - git submodule init
    - git submodule update
    - mkdir build
    - cd build
    - CXX=g++-7 cmake -DCMAKE_BUILD_TYPE=Debug -DUSE_COVERAGE=ON -DBUILD_TESTS=ON ..
    - make -j 2
    - CTEST_OUTPUT_ON_FAILURE=TRUE OMP_PROC_BIND=FALSE OMP_NUM_THREADS=3 ./unit-tests/utest-testkernel-spetabaru-float
    - lcov --directory CMakeFiles/ --directory unit-tests/CMakeFiles/ -c -o coverage-rapport.info
    - lcov --list coverage-rapport.info
    - genhtml -o ../coverage -t "Coverage tbfmm" coverage-rapport.info
  artifacts:
    paths:
      - coverage/
  stage: coverage

pages:
  stage: deploy
  dependencies:
    - tbfmm-full-coverage
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master

